name: "HTML2PDF4Doc on macOS"

on:
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    runs-on: macos-13

    strategy:
      matrix:
        python-version: [
          "3.9", "3.13"
        ]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    - name: Upgrade pip
      run: |
        python -m pip install --upgrade pip

    - name: Install minimal Python packages
      run: |
        pip install -r requirements.development.txt

    - name: Clone HTML2PDF4Doc.js
      run: |
        invoke bootstrap

    - name: Install HPDF dependencies.
      run: |
        python developer/pip_install_html2pdf4doc_deps.py

    - name: Run Lint tasks
      run: |
        invoke lint

    - name: Build HTML2PDF4Doc.js
      run: |
        invoke build

    - name: Run tests
      run: |
        invoke test
