name: HTML2Print Docker CI

on:
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6

    - name: Upgrade pip
      run: |
        python -m pip install --upgrade pip

    - name: Install Python packages
      run: |
        pip install -r requirements.development.txt

    - name: Build Docker image with PR branch
      run: |
        invoke build-docker \
          --image pr-${{ github.event.pull_request.number }} \
          --source=${{ github.event.pull_request.head.sha }}

    - name: Run container and test StrictDoc installation
      run: |
        invoke test-docker \
          --image pr-${{ github.event.pull_request.number }}
